services:
  postgres:
    image: postgres:16-alpine
    container_name: wallet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: wallet_db
    ports:
      - '5433:5432'
    volumes:
      - wallet_postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-api
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: sh -c "npm run migration:run:prod && npm run seed:admin:prod && npm run start:prod"

volumes:
  wallet_postgres_data:
